### ISSUE TITLE
Duplicate key error on sync

### ISSUE THREAD

**Issue by ktpx** [mstilkerich/rcmcarddav#366] opened 2021-11-17 21:46 UTC
Ok, adding books works, stupid server would let itself speak to the url.  

However, i get errors every time when it syncs, something about duplicate key "email-internet-3" for key 'typename'.

**Comment by ktpx** [comment] 2021-11-17 22:31
#17 {main}
[17-Nov-2021 21:36:56 +0000]: <kdhs013v> [5 ERR] Migration query (
ALTER TABLE carddav_contacts DROP INDEX `uri`, ADD UNIQUE INDEX(uri, abook_id);) failed: [1071] Specified key was too long; max key length is 767 bytes
[17-Nov-2021 21:44:30 +0000]: <t6bvkkd8> [5 ERR] Migration query (
ALTER TABLE carddav_contacts DROP INDEX `uri`, ADD UNIQUE INDEX(uri, abook_id);) failed: [1071] Specified key was too long; max key length is 767 bytes
[17-Nov-2021 22:13:12 +0000]: <km5hpvn5> [5 ERR] Migration query (
ALTER TABLE carddav_contacts DROP INDEX `uri`, ADD UNIQUE INDEX(uri, abook_id);) failed: [1071] Specified key was too long; max key length is 767 bytes
[17-Nov-2021 22:30:10 +0000]: <68csueeg> [5 ERR] Migration query (
ALTER TABLE carddav_contacts DROP INDEX `uri`, ADD UNIQUE INDEX(uri, abook_id);) failed: [1071] Specified key was too long; max key length is 767 bytes

**Comment by mstilkerich** [comment] 2021-11-18 03:50
Hello,

  please don‘t edit away the relevant content (logs), I only noticed because it was in my mail. 

I guess you are still getting the error in the logs about the failed migration. There is an issue with older MySQL / MariaDB versions concerning the limit of index keys depending on the row format and other settings for which the defaults changed in newer versions. Please see if #362 contains enough information for you to address the issue. The DB migration will run on login, you should not see any errors like those you posted on login anymore. Otherwise you don’t have the database schema expected by the code and it will not work correctly. If you cannot resolve it let me know and I‘ll try to help.

The specific issue you are seeing in usage is #306 and addressed by a later database schema adaptation that is not executed because the earlier one failed. So it should disappear once you have resolved the root issue.

**Comment by mstilkerich** [comment] 2021-11-20 12:07
You can now also try with 4.3.0, which includes the row format conversion but you would still need to set the MySQL server settings if you are using an old MySQL version where they are not the default yet.

**Comment by ktpx** [comment] 2021-11-20 12:09
Yeahm, sorry I changed the post since it was my own mistake (server blocked itself in the ip rules).   But the sync error i get all the time, I don't know.  I'm using ubuntu 18.04 lts on this box, mariadb...shouldn't be that old.  I nuked everything related to caldav in the db, and relogged.  So it works, just I get that annoying error every time.

**Comment by mstilkerich** [comment] 2021-11-20 13:01
Hello,

  the mariadb version in uhuntu 18.04 is 10.1.48 and too old. It is the same as the reported of issue #362 used. Please set the MariaDB settings listed there in your MariaDB configuration. Then the dbmigrations will succeed and the errors disappear.

At the moment you are running the plugin on an outdated DB schema that does not match the code, therefore errors like the one with the index collisions occur as a result. But the root cause is the wrong DB schema.

**Comment by ktpx** [comment] 2021-11-20 14:30
Ok thanks.  I usually run arch, not used to outdated packages ;) I will look into it, and report back.

**Comment by ktpx** [comment] 2021-11-20 14:54
innodb_large_prefix=1
innodb_file_per_table=1
innodb_file_format=Barracuda
innodb_default_row_format=dynamic

Set these in /etc/mysql/mariadb.cnf also verified its dynamic in the tables.  But I still get duplicate error.

**Comment by mstilkerich** [comment] 2021-11-20 17:28
Hmm ok, then lets first verify a few things:

* Did you restart the MariaDB server after changing the settings in mariadb.cnf?
* Please set the loglevel in plugins/carddav/config.inc.php to INFO or DEBUG, for example:
```php
$prefs['_GLOBAL']['loglevel'] = \Psr\Log\LogLevel::INFO;
```
* The database is initialized only on login to roundcube. When starting with a clean database (i.e. without any carddav_* tables), the carddav.log file should show these INFO-level log messages on successfull schema initialization. it is important that you see that all migrations up to the last one are done, because if there is an error with one the db initialization will abort at that step (and retry to continue from there on next login to roundcube):
```
[2021-11-20 10:45:28] INFO: [2 NFO] Found 6 queries in /somepath/dbmigrations/0000-dbinit/mysql.sql
[2021-11-20 10:45:28] INFO: [2 NFO] Found 1 queries in /somepath/dbmigrations/0001-categories/mysql.sql
[2021-11-20 10:45:28] INFO: [2 NFO] Found 2 queries in /somepath/dbmigrations/0002-increasetextfieldlengths/mysql.sql
[2021-11-20 10:45:28] INFO: [2 NFO] Found 1 queries in /somepath/dbmigrations/0003-fixtimestampdefaultvalue/mysql.sql
[2021-11-20 10:45:28] INFO: [2 NFO] Found 1 queries in /somepath/dbmigrations/0004-fixtimestampdefaultvalue/mysql.sql
[2021-11-20 10:45:28] INFO: [2 NFO] Found 41 queries in /somepath/dbmigrations/0005-changemysqlut8toutf8mb4/mysql.sql
[2021-11-20 10:45:29] INFO: [2 NFO] Found 5 queries in /somepath/dbmigrations/0006-rmgroupsnotnull/mysql.sql
[2021-11-20 10:45:29] INFO: [2 NFO] Found 1 queries in /somepath/dbmigrations/0008-unifyindexes/mysql.sql
[2021-11-20 10:45:29] INFO: [2 NFO] Found 1 queries in /somepath/dbmigrations/0009-dropauthschemefield/mysql.sql
[2021-11-20 10:45:29] INFO: [2 NFO] Found 7 queries in /somepath/dbmigrations/0010-increasetextfieldlengths/mysql.sql
[2021-11-20 10:45:29] INFO: [2 NFO] Found 1 queries in /somepath/dbmigrations/0011-unifymigrationsidcolumn/mysql.sql
[2021-11-20 10:45:29] INFO: [2 NFO] Found 27 queries in /somepath/dbmigrations/0012-fixmysqlconstraints/mysql.sql
[2021-11-20 10:45:30] INFO: [2 NFO] Found 36 queries in /somepath/dbmigrations/0013-changemysqlcollationscasesensitive/mysql.sql
[2021-11-20 10:45:31] INFO: [2 NFO] Found 7 queries in /somepath/dbmigrations/0014-unifytimestampdefaultvalue/mysql.sql
[2021-11-20 10:45:31] INFO: [2 NFO] Found 2 queries in /somepath/dbmigrations/0015-fixmysqlconstraints/mysql.sql
```
* When all this has successfully finished, you should also find the migrations recorded in the `carddav_migrations` table, which you can check with a MySQL client. If any are missing here, you are not using the current DB schema:
```
mysql> select * from carddav_migrations;
+----+-----------------------------------------+---------------------+
| id | filename                                | processed_at        |
+----+-----------------------------------------+---------------------+
|  1 | 0000-dbinit                             | 2021-11-20 11:45:28 |
|  2 | 0001-categories                         | 2021-11-20 11:45:28 |
|  3 | 0002-increasetextfieldlengths           | 2021-11-20 11:45:28 |
|  4 | 0003-fixtimestampdefaultvalue           | 2021-11-20 11:45:28 |
|  5 | 0004-fixtimestampdefaultvalue           | 2021-11-20 11:45:28 |
|  6 | 0005-changemysqlut8toutf8mb4            | 2021-11-20 11:45:29 |
|  7 | 0006-rmgroupsnotnull                    | 2021-11-20 11:45:29 |
|  8 | 0007-replaceurlplaceholders             | 2021-11-20 11:45:29 |
|  9 | 0008-unifyindexes                       | 2021-11-20 11:45:29 |
| 10 | 0009-dropauthschemefield                | 2021-11-20 11:45:29 |
| 11 | 0010-increasetextfieldlengths           | 2021-11-20 11:45:29 |
| 12 | 0011-unifymigrationsidcolumn            | 2021-11-20 11:45:29 |
| 13 | 0012-fixmysqlconstraints                | 2021-11-20 11:45:30 |
| 14 | 0013-changemysqlcollationscasesensitive | 2021-11-20 11:45:31 |
| 15 | 0014-unifytimestampdefaultvalue         | 2021-11-20 11:45:31 |
| 16 | 0015-fixmysqlconstraints                | 2021-11-20 11:45:31 |
+----+-----------------------------------------+---------------------+
16 rows in set (0.00 sec)
```
* The carddav tables (of particular index here is index length, engine / row format and collation) should look like this:
```
mysql> show table status where Name like 'carddav_%';
+----------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------+----------+--------------------+---------+
| Name                 | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation   | Checksum | Create_options     | Comment |
+----------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------+----------+--------------------+---------+
| carddav_addressbooks | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        16384 |         0 |              1 | 2021-11-20 11:45:31 | NULL        | NULL       | utf8mb4_bin |     NULL | row_format=DYNAMIC |         |
| carddav_contacts     | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        49152 |         0 |              1 | 2021-11-20 11:45:30 | NULL        | NULL       | utf8mb4_bin |     NULL | row_format=DYNAMIC |         |
| carddav_group_user   | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        16384 |         0 |           NULL | 2021-11-20 11:45:30 | NULL        | NULL       | utf8mb4_bin |     NULL | row_format=DYNAMIC |         |
| carddav_groups       | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        49152 |         0 |              1 | 2021-11-20 11:45:30 | NULL        | NULL       | utf8mb4_bin |     NULL | row_format=DYNAMIC |         |
| carddav_migrations   | InnoDB |      10 | Dynamic    |   16 |           1024 |       16384 |               0 |        16384 |         0 |             17 | 2021-11-20 11:45:31 | NULL        | NULL       | utf8mb4_bin |     NULL | row_format=DYNAMIC |         |
| carddav_xsubtypes    | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        32768 |         0 |              1 | 2021-11-20 11:45:31 | NULL        | NULL       | utf8mb4_bin |     NULL | row_format=DYNAMIC |         |
+----------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------+----------+--------------------+---------+
6 rows in set (0.00 sec)
```

If all of this looks good, then please let me know the context of `carddav_xsubtypes` table on which you get the duplicate key error, which should look something like this (instead of the 14 insert the actual addressbook ID for that you get the error, it is the last part of the composed key - in your error message, it was 3):
```
mysql> select * from carddav_xsubtypes where abook_id=14;
+----+----------+---------+----------+
| id | typename | subtype | abook_id |
+----+----------+---------+----------+
| 10 | email    | Email   |       14 |
|  9 | email    | Other   |       14 |
+----+----------+---------+----------+
2 rows in set (0.00 sec)
```
If you still have the same error, you should see a row there with typename = email and subtype = internet. Then it would be helpful to know the content of the vcard for that the import fails (particularly the EMAIL properties and their TYPE and possible X-ABLABEL properties).

**Comment by ktpx** [comment] 2021-11-20 17:37
I think it's ok now.  I put the db confif params under client-server section first, i added [server] and put it under there instead Seems that fixed it.   Thanks :D

**Comment by mstilkerich** [comment] 2021-11-20 18:20
Great if it works for you! I'll close this issue then.

**Closed by mstilkerich** 2021-11-20 18:20 UTC

**Comment by ktpx** [comment] 2021-11-20 19:16
Yes, go head. Thanks again, thanks for the help.
