### ISSUE TITLE
Install fails with Roundcube 1.6

### ISSUE THREAD

**Issue by cmlnet** [mstilkerich/rcmcarddav#388] opened 2022-07-29 05:55 UTC
I just upgraded to roundcube 1.6 as the latest stable version. After the upgrade, I ran `composer update --no-dev`as recommended by roundcube.

Unfortunately, this leads to the following failure with RCMCardDav:

```
- Downloading roundcube/carddav (v4.4.2)
Update of roundcube/carddav failed

In autoload_real.php line 82:
                                                                                                              
require(/var/www/mail.c-m-l.net/vendor/composer/../symfony/polyfill-php72/bootstrap.php): Failed to open stream: No such file or directory
```

I have no idea what could cause that problem.

The server runs PHP 8.0

**Comment by cmlnet** [comment] 2022-07-29 06:32
Update: After removing the plugin by deleting its folder, an update and subsequent reinstallation worked just fine.

**Comment by darren12345** [comment] 2022-07-29 08:34
I had the same problem as the update removed the polyfill-php72 plugin. I added it as a required plugin in the composer.json but am hitting this similar error:
```
Package operations: 1 install, 0 updates, 0 removals
    Install of roundcube/carddav failed

In autoload_real.php line 59:

  require(/home/web/mail/vendor/composer/../guzzlehttp/psr7/src/functions_include.php): failed to open stream: No such file or directory
```

The psr7 plugin was upgraded but is still there, but I have added it as a required plugin also, but am still hitting this error. Removed the carddav directory and reinstalled as per cmlnet's suggestion, but no joy.

**Comment by darren12345** [comment] 2022-07-29 08:57
Resolved with some combination of removing carddav (`php composer.phar remove "roundcube/carddav"`), which did initially fail with the same error, but removed the ../vendor directory, removed it again, updated and installed again.

**Comment by mstilkerich** [comment] 2022-07-29 18:42
Hmm, I know I have had this issue before, too, but unfortunately I cannot reproduce it at the moment. I tried unpacking an 1.5.3 archive, installed rcmcarddav using the command listed in INSTALL.md, the upgraded that folder to 1.6.0 using roundcube's bin/installto.sh command, and then ran 

```
composer update --no-dev -o
Loading composer repositories with package information
Updating dependencies
Lock file operations: 8 installs, 22 updates, 5 removals
  - Removing paragonie/random_compat (v2.0.21)
  - Removing phpunit/phpunit-mock-objects (2.3.8)
  - Removing symfony/polyfill-ctype (v1.19.0)
  - Removing symfony/polyfill-php70 (v1.19.0)
  - Removing symfony/yaml (v2.8.52)
  - Upgrading doctrine/instantiator (1.0.5 => 1.4.1)
  - Locking myclabs/deep-copy (1.11.0)
  - Locking phar-io/manifest (1.0.3)
  - Locking phar-io/version (2.0.1)
  - Upgrading phpdocumentor/reflection-common (1.0.1 => 2.2.0)
  - Upgrading phpdocumentor/reflection-docblock (3.2.2 => 5.3.0)
  - Upgrading phpdocumentor/type-resolver (0.3.0 => 1.6.1)
  - Upgrading phpspec/prophecy (v1.10.3 => v1.15.0)
  - Upgrading phpunit/php-code-coverage (2.2.4 => 6.1.4)
  - Upgrading phpunit/php-file-iterator (1.4.5 => 2.0.5)
  - Upgrading phpunit/php-timer (1.0.9 => 2.1.3)
  - Upgrading phpunit/php-token-stream (1.4.12 => 3.1.3)
  - Upgrading phpunit/phpunit (4.8.36 => 7.5.20)
  - Upgrading ralouphie/getallheaders (2.0.5 => 3.0.3)
  - Locking sebastian/code-unit-reverse-lookup (1.0.2)
  - Upgrading sebastian/comparator (1.2.4 => 3.0.3)
  - Upgrading sebastian/diff (1.4.3 => 3.0.3)
  - Upgrading sebastian/environment (1.3.8 => 4.2.4)
  - Upgrading sebastian/exporter (1.2.2 => 3.1.4)
  - Upgrading sebastian/global-state (1.1.1 => 2.0.0)
  - Locking sebastian/object-enumerator (3.0.4)
  - Locking sebastian/object-reflector (1.1.2)
  - Upgrading sebastian/recursion-context (1.0.5 => 3.0.1)
  - Locking sebastian/resource-operations (2.0.2)
  - Upgrading sebastian/version (1.0.6 => 2.0.1)
  - Upgrading symfony/polyfill-intl-idn (v1.19.0 => v1.26.0)
  - Upgrading symfony/polyfill-intl-normalizer (v1.19.0 => v1.26.0)
  - Upgrading symfony/polyfill-php72 (v1.19.0 => v1.26.0)
  - Locking theseer/tokenizer (1.2.1)
  - Upgrading webmozart/assert (1.9.1 => 1.11.0)
Writing lock file
Installing dependencies from lock file
Package operations: 0 installs, 4 updates, 2 removals
  - Removing symfony/polyfill-php70 (v1.19.0)
  - Removing paragonie/random_compat (v2.0.21)
  - Upgrading symfony/polyfill-php72 (v1.19.0 => v1.26.0): Extracting archive
  - Upgrading symfony/polyfill-intl-normalizer (v1.19.0 => v1.26.0): Extracting archive
  - Upgrading symfony/polyfill-intl-idn (v1.19.0 => v1.26.0): Extracting archive
  - Upgrading ralouphie/getallheaders (2.0.5 => 3.0.3): Extracting archive
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
6 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

polyfill-php72 is removed without error. I don't think the issue is related to rcmcarddav as it does not do anything "special" with respect to its usage of composer (like code hooks or whatever)...

**Comment by mstilkerich** [comment] 2022-07-31 06:25
Hello,

 I have taken a look at how the roundcube upgrade process works concerning the vendor directory when upgrading using `bin/installto.sh`:
- If composer.json already exists in the target, which would be the case if you installed rcmcarddav using composer, the vendor directory is left untouched by the upgrade script. That means, after running the script, the dependencies inside the vendor directory don't fit with the new roundcube version and therefore it is necessary to run `composer update` first, which is also highlighted in the console output of the update script.
- The update script also patches the existing `composer.json` such that the dependencies are updated to match the new roundcube version. The requirements for custom packages like rcmcarddav are retained in the process. 
- When running composer update, the vendor directory should get fixed up for the new roundcube version.

The problem appears to be the plugin code of roundcube/plugin-installer which is executed on attempt to upgrade rcmcarddav during the process, because this code apparently causes the composer autoloader to be called. However, during the install step, composer has removed some package like polyfill-php72 and apparently the autoloader was not updated by the time the code of  roundcube/plugin-installer, and cannot find those files anymore. I cannot say if this is a problem with roundcube/plugin-installer or with the install process of composer itself with respect to plugin code.

### Workaround
To workaround the error, after composer update has failed with the above error, you can run `composer dump-autoload` to update the autoloader. Afterwards, simply repeat the `composer update --no-dev` run and this time it should succeed.

**Comment by mstilkerich** [comment] 2022-07-31 06:40
Filed an issue at plugin installer: roundcube/plugin-installer#38

**Comment by mstilkerich** [comment] 2022-07-31 12:31
I‘m closing the issue as it is not a problem of rcmcarddav.

**Closed by mstilkerich** 2022-07-31 12:31 UTC

**Comment by cmlnet** [comment] 2022-08-03 07:30
Thank you very much for your efforts, @mstilkerich.
