### ISSUE TITLE
error when clicking on a contact folder in parameter page

### ISSUE THREAD

**Issue by quenenni** [mstilkerich/rcmcarddav#437] opened 2023-04-21 12:56 UTC
When I go to the parameter page -> Carddav section -> Click on one of the addressbooks in the middle column, I have this error:
```
==> errors.log <==
[21-Apr-2023 14:53:35 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method MStilkerich\CardDavClient\AddressbookCollection::getDisplayName() in /var/www/roundcube-test/plugins/carddav/src/Frontend/UI.php:810
Stack trace:
#0 /var/www/roundcube-test/plugins/carddav/src/Frontend/UI.php(988): MStilkerich\RCMCardDAV\Frontend\UI->getEnhancedAbookConfig()
#1 /var/www/roundcube-test/program/include/rcmail_output_html.php(1484): MStilkerich\RCMCardDAV\Frontend\UI->tmplAddressbookDetails()
#2 [internal function]: rcmail_output_html->xml_command()
#3 /var/www/roundcube-test/program/include/rcmail_output_html.php(1322): preg_replace_callback()
#4 /var/www/roundcube-test/program/include/rcmail_output_html.php(825): rcmail_output_html->parse_xml()
#5 /var/www/roundcube-test/program/include/rcmail_output_html.php(654): rcmail_output_html->parse()
#6 /var/www/roundcube-test/plugins/carddav/carddav.php(297): rcmail_output_html->send()
#7 /var/www/roundcube-test/plugins/carddav/src/Frontend/UI.php(645): carddav->sendTemplate()
#8 /var/www/roundcube-test/program/lib/Roundcube/rcube_plugin_api.php(575): MStilkerich\RCMCardDAV\Frontend\UI->actionAbDetails()
#9 /var/www/roundcube-test/program/include/rcmail.php(255): rcube_plugin_api->exec_action()
#10 /var/www/roundcube-test/index.php(278): rcmail->action_handler()
#11 {main}
  thrown in /var/www/roundcube-test/plugins/carddav/src/Frontend/UI.php on line 810
```

Seems to be the same problem as #436 

[EDIT]
If I click on the "Address Book" in the middle column, no error and it shows the config of all the adress books in the right column.
The error is only when clicking on a specific address book in the middle column.

**Comment by mstilkerich** [comment] 2023-04-21 15:13
Duplicate of #436

**Closed by mstilkerich** 2023-04-21 15:13 UTC
Labels: duplicate
