### ISSUE TITLE
Account creation: Argument 2 must be of the type string, array given

### ISSUE THREAD

**Issue by mcnesium** [mstilkerich/rcmcarddav#370] opened 2021-12-01 14:57 UTC
After upgrading RC from 1.4.x to 1.5.1 the configured CardDAV address book returned "internal error" notes when typing addresses. So I deleted the account and tried to recreate it: inserted name, username, password, Nextcloud-CardDAV URL and 1 for the update interval, and hit `Save`. It returned a big "Oops... something went wrong!" and in the server logs I found this:

    PHP Fatal error:  Uncaught TypeError: Argument 2 passed to MStilkerich\\CardDavClient\\Account::__construct() must be of the type string, array given, called in /var/www/html/plugins/carddav/src/Config.php on line 161 and defined in /var/www/html/vendor/mstilkerich/carddavclient/src/Account.php:50
    Stack trace:
    #0 /var/www/html/plugins/carddav/src/Config.php(161): MStilkerich\\CardDavClient\\Account->__construct('https://cloud.e...', Array, '', NULL)
    #1 /var/www/html/plugins/carddav/carddav.php(619): MStilkerich\\CardDavAddressbook4Roundcube\\Config::makeAccount('https://cloud.e...', 'xxxxxxxx', 'xxxxxxxxxxxxxxxx', NULL)
    #2 /var/www/html/program/lib/Roundcube/rcube_plugin_api.php(513): carddav->savePreferences(Array)
    #3 /var/www/html/program/actions/settings/prefs_save.php(165): rcube_plugin_api->exec_hook('preferences_sav...', Array)
    #4 /var/www/html/program/include/rcmail.php(275): rcmail_action_settings_prefs_save->run(Array)
    #5 /var/www/html/index.php(283): rcmail->action_handler()
    #6 {main}
    thrown in /var/www/html/vendor/mstilkerich/carddavclient/src/Account.php on line 50, referer: https://roundcube.e.../?_task=settings&_action=edit-prefs&_section=cd_preferences&_framed=1

I x-ed out user name and password, because both appear in clear text in the log.

Did I break something? What is this error about? How can I fix it?

**Comment by mstilkerich** [comment] 2021-12-01 20:27
Hello,

  this is not related to your roundcube upgrade, but I guess at some point you upgraded rcmcarddav from a version <4.2 to a 4.2 or newer version. To support oauth authentication, rcmcarddav from 4.2 needs a more recent version of mstilkerich/carddavclient. You are getting this error because the version you have loaded is too old.

The solution is to upgrade you carddavclient lib. But normally this happens automatically when you upgrade rcmcarddav. When you install/upgrade using composer, composer would also update carddavclient because of the changed dependency. When you install via tarball, the proper version is bundled in the tarball. Is it possible that you mixed the installation approaches and now maybe have two versions of carddavclient in your installation, of which the old one gets loaded? You can check if there is a vendor subdirectory in the carddav plugin dir, and the vendor subdirectory at the roundcube main directory also contains an mstilkerich/carddavclient subdirectory. This is my best guess.

**Comment by mcnesium** [comment] 2021-12-02 08:44
How do I do a manual upgrade of a dependency? Shouldn't Composer take care of that? Actually everything is installed in a Docker image [derived from the official docs](https://github.com/roundcube/roundcubemail-docker#building-a-docker-image) using only `composer require roundcube/carddav`, see full Dockerfile in the details. So only the database really was "upgraded".

<details>

    FROM roundcube/roundcubemail:latest

    COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

    # install git and unzip
    RUN \
        set -ex; \
        apt-get update; \
        apt-get install -y --no-install-recommends \
            git \
            unzip \
        ;

    # configure composer
    RUN \
        mv /usr/src/roundcubemail/composer.json-dist /usr/src/roundcubemail/composer.json \
        ;

    # install roundcube addons
    RUN \
        composer \
            --working-dir=/usr/src/roundcubemail/ \
            require \
                roundcube/carddav \
        ;

    # update dependencies
    RUN \
        composer \
            --working-dir=/usr/src/roundcubemail/ \
            --prefer-dist --no-dev \
            --no-interaction \
            --optimize-autoloader --apcu-autoloader \
            update \
        ;

    # install identity_smtp with dev stability
    RUN \
        composer config --file=/usr/src/roundcubemail/composer.json minimum-stability dev; \
        composer \
            --working-dir=/usr/src/roundcubemail/ \
            require \
                elm/identity_smtp:=dev-master \
        ;

</details>

**Comment by mstilkerich** [comment] 2021-12-02 10:51
Hello, yes composer should handle it. When you build the image, what version of mstilkerich/carddavclient is pulled by composer? It should be a version 1.2 or higher. See below for example output (I only removed net_ldap because my PHP installation lacks required extensions).

<details>

```
mikey@forge[/tmp] tar xzf roundcubemail-1.5.1-complete.tar.gz
mikey@forge[/tmp] cd roundcubemail-1.5.1
mikey@forge[roundcubemail-1.5.1] grep -v net_ldap composer.json-dist >composer.json
mikey@forge[roundcubemail-1.5.1] composer require --update-no-dev --no-progress roundcube/carddav
Using version ^4.3 for roundcube/carddav
./composer.json has been updated
Running composer update roundcube/carddav
Loading composer repositories with package information
Updating dependencies
Lock file operations: 7 installs, 0 updates, 2 removals
  - Removing kolab/net_ldap3 (v1.1.3)
  - Removing pear/net_ldap2 (v2.2.0)
  - Locking mstilkerich/carddavclient (v1.2.1)
  - Locking psr/http-client (1.0.1)
  - Locking psr/log (1.1.4)
  - Locking roundcube/carddav (v4.3.0)
  - Locking sabre/uri (2.2.2)
  - Locking sabre/vobject (4.4.0)
  - Locking sabre/xml (2.2.5)
Writing lock file
Installing dependencies from lock file
Package operations: 7 installs, 0 updates, 2 removals
  - Removing pear/net_ldap2 (v2.2.0)
  - Removing kolab/net_ldap3 (v1.1.3)
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing psr/log (1.1.4): Extracting archive
  - Installing sabre/uri (2.2.2): Extracting archive
  - Installing sabre/xml (2.2.5): Extracting archive
  - Installing sabre/vobject (4.4.0): Extracting archive
  - Installing mstilkerich/carddavclient (v1.2.1): Extracting archive
  - Installing roundcube/carddav (v4.3.0): Extracting archive
Creating package config file
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
6 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

</details>

**Comment by mcnesium** [comment] 2021-12-02 11:01
it is installing `v1.2.1`, see full output of the `RUN` command in details.

<details>

    Step 5/9 : RUN   composer   --working-dir=/usr/src/roundcubemail/   require   roundcube/carddav ;
    ---> Running in 518a5e9e924c
    Using version ^4.3 for roundcube/carddav
    ./composer.json has been updated
    Running composer update roundcube/carddav
    Loading composer repositories with package information
    Updating dependencies
    Lock file operations: 7 installs, 0 updates, 2 removals
      - Removing kolab/net_ldap3 (v1.1.3)
      - Removing pear/net_ldap2 (v2.2.0)
      - Locking mstilkerich/carddavclient (v1.2.1)
      - Locking psr/http-client (1.0.1)
      - Locking psr/log (1.1.4)
      - Locking roundcube/carddav (v4.3.0)
      - Locking sabre/uri (2.2.2)
      - Locking sabre/vobject (4.4.0)
      - Locking sabre/xml (2.2.5)
    Writing lock file
    Installing dependencies from lock file (including require-dev)
    Package operations: 29 installs, 0 updates, 2 removals
      - Downloading symfony/polyfill-ctype (v1.19.0)
      - Downloading webmozart/assert (1.9.1)
      - Downloading phpdocumentor/reflection-common (1.0.1)
      - Downloading phpdocumentor/type-resolver (0.3.0)
      - Downloading phpdocumentor/reflection-docblock (3.2.2)
      - Downloading phpunit/php-token-stream (1.4.12)
      - Downloading symfony/yaml (v2.8.52)
      - Downloading sebastian/version (1.0.6)
      - Downloading sebastian/global-state (1.1.1)
      - Downloading sebastian/recursion-context (1.0.5)
      - Downloading sebastian/exporter (1.2.2)
      - Downloading sebastian/environment (1.3.8)
      - Downloading sebastian/diff (1.4.3)
      - Downloading sebastian/comparator (1.2.4)
      - Downloading phpunit/php-text-template (1.2.1)
      - Downloading doctrine/instantiator (1.0.5)
      - Downloading phpunit/phpunit-mock-objects (2.3.8)
      - Downloading phpunit/php-timer (1.0.9)
      - Downloading phpunit/php-file-iterator (1.4.5)
      - Downloading phpunit/php-code-coverage (2.2.4)
      - Downloading phpspec/prophecy (v1.10.3)
      - Downloading phpunit/phpunit (4.8.36)
      - Downloading psr/http-client (1.0.1)
      - Downloading psr/log (1.1.4)
      - Downloading sabre/uri (2.2.2)
      - Downloading sabre/xml (2.2.5)
      - Downloading sabre/vobject (4.4.0)
      - Downloading mstilkerich/carddavclient (v1.2.1)
      - Downloading roundcube/carddav (v4.3.0)
    29/29 [============================] 100%
      - Removing pear/net_ldap2 (v2.2.0)
      - Removing kolab/net_ldap3 (v1.1.3)
      - Installing symfony/polyfill-ctype (v1.19.0): Extracting archive
      - Installing webmozart/assert (1.9.1): Extracting archive
      - Installing phpdocumentor/reflection-common (1.0.1): Extracting archive
      - Installing phpdocumentor/type-resolver (0.3.0): Extracting archive
      - Installing phpdocumentor/reflection-docblock (3.2.2): Extracting archive
      - Installing phpunit/php-token-stream (1.4.12): Extracting archive
      - Installing symfony/yaml (v2.8.52): Extracting archive
      - Installing sebastian/version (1.0.6): Extracting archive
      - Installing sebastian/global-state (1.1.1): Extracting archive
      - Installing sebastian/recursion-context (1.0.5): Extracting archive
      - Installing sebastian/exporter (1.2.2): Extracting archive
      - Installing sebastian/environment (1.3.8): Extracting archive
      - Installing sebastian/diff (1.4.3): Extracting archive
      - Installing sebastian/comparator (1.2.4): Extracting archive
      - Installing phpunit/php-text-template (1.2.1): Extracting archive
      - Installing doctrine/instantiator (1.0.5): Extracting archive
      - Installing phpunit/phpunit-mock-objects (2.3.8): Extracting archive
      - Installing phpunit/php-timer (1.0.9): Extracting archive
      - Installing phpunit/php-file-iterator (1.4.5): Extracting archive
      - Installing phpunit/php-code-coverage (2.2.4): Extracting archive
      - Installing phpspec/prophecy (v1.10.3): Extracting archive
      - Installing phpunit/phpunit (4.8.36): Extracting archive
      - Installing psr/http-client (1.0.1): Extracting archive
      - Installing psr/log (1.1.4): Extracting archive
      - Installing sabre/uri (2.2.2): Extracting archive
      - Installing sabre/xml (2.2.5): Extracting archive
      - Installing sabre/vobject (4.4.0): Extracting archive
      - Installing mstilkerich/carddavclient (v1.2.1): Extracting archive
      - Installing roundcube/carddav (v4.3.0): Extracting archive
    29/29 [============================] 100%Creating package config file
    1 package suggestions were added by new dependencies, use `composer suggest` to see details.
    Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
    Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
    Generating autoload files
    7 packages you are using are looking for funding.
    Use the `composer fund` command to find out more!
    Removing intermediate container 518a5e9e924c

</details>

**Comment by mstilkerich** [comment] 2021-12-02 14:01
Hello, I built the container using your dockerfile and it works perfectly fine. The error message you posted is definitely caused by a too old carddavclient library. The output you posted looks good, so if this error message really occurs for that container I have no clue why.

**Comment by mstilkerich** [comment] 2021-12-07 18:09
Hello,

  are you still investigating this? I cannot reproduce the issue on my end, so without new information I cannot help. If you have given up / lost interest on this, please close the issue. Otherwise I will close the issue in a couple of days without feedback.

**Comment by mcnesium** [comment] 2021-12-08 08:02
It's still unsolved but I could not get back to further investigation yet, sorry. I guess I will need to set up a full extra instance first, to test whether this happens there too.

**Comment by mstilkerich** [comment] 2021-12-21 16:34
Since there is no updates here and no issue present within rcmcarddav for all I can see, I‘m closing this. If you want to follow up on this, just reopen or create a new issue or discussion.

**Closed by mstilkerich** 2021-12-21 16:34 UTC
