### ISSUE TITLE
php fatal error when carddav tries to sync

### ISSUE THREAD

**Issue by rodrigoesborges** [mstilkerich/rcmcarddav#329] opened 2021-01-28 03:06 UTC
Roundcube 1.4.10
carddav plugin v4.1.0+dev

Just upgraded from old 1.2.4 , where I had a non functioning carddav plugin enabled before.

may be related to #150 

PHP Fatal error:  Uncaught TypeError: Argument 4 passed to MStilkerich\CardDavClient\Services\Sync::synchronize() must be of the type string, null given, called in XXX/plugins/carddav/src/Addressbook.php on line 1090 and defined in XXX/vendor/mstilkerich/carddavclient/src/Services/Sync.php:49

I get empty carddav contact list even though it shows as setup and even shows a last time sync on roundcube config UI for it.

Sorry if I am missing anything obvious (I am not a  programmer / computer scientist/engineer, just an enthusiast that has been trying to use and tinker some self-hosted free software).

**Comment by mstilkerich** [comment] 2021-01-28 06:14
Hello, the sync token cannot be null per database constraint. Is it possible that you have some old tables from a v1 or v2 plugin left? There was no automatic upgrade to the newer versions. I would suggest to log out of roundcube, drop all carddav_* tables from the roundcube database and login again. Then the tables will be created from scratch.

**Comment by mstilkerich** [comment] 2021-02-01 16:27
Hello, are you still interested in fixing this? If not, I will close this issue in a couple of days.

**Comment by mstilkerich** [comment] 2021-02-04 13:29
Closing this issue as I cannot reproduce it and no reply from issue creator.

**Comment by mstilkerich** [comment] 2021-02-25 18:31
The NOT NULL DEFAULT ¨" constraint is missing in the mysql schema.

**Comment by mstilkerich** [comment] 2021-02-26 16:09
Fixed with e9f4f85dacf05ed3b4f8c3e4ac00114ef25a49e1

**Closed by mstilkerich** 2021-02-26 16:09 UTC
