### ISSUE TITLE
rcmcarddav not working with roundcube 1.6.1 anymore?

### ISSUE THREAD

**Issue by Sailing74** [mstilkerich/rcmcarddav#431] opened 2023-04-02 10:20 UTC
Trying to update my working 1.6.0 installation to 1.6.1 (by using the installto.sh script and then running php composer.phar update --no-dev) leaves me with a non-working installation of roundcube, with the error coming from rcmcarddav:

[code][02-Apr-2023 12:10:29 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class "MStilkerich\CardDavAddressbook4Roundcube\Config" not found in /var/www/roundcube/plugins/carddav/carddav.php:172
Stack trace:
#0 /var/www/roundcube/program/lib/Roundcube/rcube_plugin_api.php(105): carddav->init()
#1 /var/www/roundcube/program/include/rcmail.php(160): rcube_plugin_api->init()
#2 /var/www/roundcube/program/include/rcmail.php(93): rcmail->startup()
#3 /var/www/roundcube/index.php(43): rcmail::get_instance()
#4 /var/www/roundcube/public_html/index.php(26): include('...')
#5 {main}
  thrown in /var/www/roundcube/plugins/carddav/carddav.php on line 172[/code]

If I go back to 1.6.0, roundcube works, no error from rcmcarddav.

Any chance to get rcmcarddav running also with RC 1.6.1?

Thanks!

**Comment by mstilkerich** [comment] 2023-04-02 10:35
Rcmcarddav runs fine with 1.6.1. How did you install rcmcarddav, using composer? Did the composer update report any errors?

It’s probably the simplest to just delete the carddav directory (save your config.inc.php first if you have one) and reinstall rcmcarddav by running composer like you did.

**Comment by Sailing74** [comment] 2023-04-02 12:27
Thanks, deleted the carddav directory and ran

`sudo -u www-data php composer.phar require --update-no-dev -o "roundcube/carddav:*"`

Besides some Deprecation notes, I got this:

```
 - Installing mstilkerich/carddavclient (v1.3.0): Extracting archive
ERROR: Failed to load plugin file /var/www/roundcube/plugins/carddav/carddav.php
  - Installing roundcube/carddav (v5.0.1): Extracting archive
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilenameFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///var/www/roundcube/composer.phar/vendor/symfony/finder/Iterator/FilenameFilterIterator.php:28
 2/3 [==================>---------]  66%Do you want to activate the plugin carddav? [Y|n] Y
```
Despite this erroor, after installation /var/www/roundcube/plugins/carddav/carddav.php does exist.

errors.log says:

`[02-Apr-2023 14:07:24 +0200]: <onmi3b2c> DB Error: [1146] Table 'roundcube.carddav_accounts' doesn't exist (SQL Query: SELECT * FROM carddav_accounts WHERE ((`user_id` = '1'))) in /var/www/roundcube/program/lib/Roundcube/rcube_db.php on line 567 (GET /)
`

rcmcarddav installed in the working roundcube is 4.1.1. As roundcube doesn't load, no login is possible, so probably a necessary automatic database upgrade hasn't happened, yet...? But with roundcube not loading and just showing the "Oops... something went wrong!" page, I won't be able to login to start database migration.

**Comment by mstilkerich** [comment] 2023-04-02 12:48
What does the roundcube error.log say? The missing database table will be created on login. If the issue is that some class could not be found, it might help to create the autoloader again.

See here for the commands
https://github.com/mstilkerich/rcmcarddav/blob/master/doc/INSTALL.md#update-using-composer

**Comment by Sailing74** [comment] 2023-04-02 13:11
This is from the roundcube errors.log:

`[02-Apr-2023 14:07:24 +0200]: <onmi3b2c> DB Error: [1146] Table 'roundcube.carddav_accounts' doesn't exist (SQL Query: SELECT * FROM carddav_accounts WHERE ((user_id= '1'))) in /var/www/roundcube/program/lib/Roundcube/rcube_db.php on line 567 (GET /)
`

I will fiddle around with this some more later, when I find more time. Thanks.

**Comment by mstilkerich** [comment] 2023-04-03 16:53
I'd suggest to turn the loglevel in `config.inc.php` to debug, and log in to roundcube. You should see  the database migrations taking place, or error message in case one of them fails. If you don't see the migrations happening, please check the `carddav_migrations` table's content regarding which migrations have been entered there (which should only happen if those migrations where successfully performed).

**Comment by mstilkerich** [comment] 2023-04-13 19:21
Any update?

**Comment by Sailing74** [comment] 2023-04-13 19:43
Not yet, real life is a bit demanding these days...

**Comment by mstilkerich** [comment] 2023-04-21 15:20
Closing this since there has not been an update in weeks and I believe there is no error within rcmcarddav. Feel free to open a new issue if you want to follow up on this.

**Closed by mstilkerich** 2023-04-21 15:20 UTC
