### ISSUE TITLE
Declaration error log(..., Stringable|string,...): void

### ISSUE THREAD

**Issue by jeremitu** [mstilkerich/rcmcarddav#460] opened 2023-12-15 12:00 UTC
I get the following declaration error, solved by changing the method signature to `public function log($level, string|\Stringable $message, array $context = array()): void`
```
PHP Fatal error:  Declaration of MStilkerich\CardDavAddressbook4Roundcube\RoundcubeLogger::log($level, string $message, array $context = []): void must be compatible with Psr\Log\AbstractLogger::log($level, Stringable|string $message, array $context = []): void in /usr/local/lib/roundcubemail/plugins/carddav/src/RoundcubeLogger.php on line 99
```

**Comment by mstilkerich** [comment] 2023-12-26 18:16
Hmm, which version of PHP do you use? I cannot use your fix since union types are only available starting PHP 8.0, but RCMCardDAV 5.x still supports 7.4.

The method interface in Rcmcarddav should be fine as the message parameter is more generic than in the interface definition, that is at least my understanding (https://www.php.net/manual/en/language.oop5.variance.php). I also don't see this error, at least with PHP 8.2.

Could you provide the output of `composer show` and `composer show -p` that should show all the installed packages as well as the PHP platform module versions?

**Comment by jeremitu** [comment] 2023-12-29 09:44
It is PHP 8.0.3. Here is the version comparison between my old box (all fine) and the new one (requiring fix).
[box_old.txt](https://github.com/mstilkerich/rcmcarddav/files/13792382/box_old.txt)
[box_new.txt](https://github.com/mstilkerich/rcmcarddav/files/13792384/box_new.txt)

**Comment by mstilkerich** [comment] 2024-01-03 19:38
I don't see any interesting differences in those two. However, what is interesting is that according to the composer outputs, psr/log version 1.1.4 is installed, which is a version that lacks the types in the parameter definitions:
https://github.com/php-fig/log/blob/d49695b909c3b7628b6289db5479a1c204601f11/Psr/Log/LoggerInterface.php#L124

What I mean to say is - you cannot get this error message with version 1.1.4 of the psr/log library, because it does not define 
`Stringable|string $message` parameter but just a generic `$message`. So it appears you have another version of psr/log in your PHP include path / autoloaders that take precedence over the one installed with RCMCardDAV.

But even using the latest v3 version of psr/log I cannot reproduce the error message you get, and for the reasons stated in my last comment I also would not expect an error as the RCMCardDAV class allows a wider type than the interface it implements, which should be fine.

A probably unrelated note: You should install RCMCardDAV using composer. For example you can see in your listings, that you have two different major versions of Guzzle installed. It is a potential source of problems, although I do not see I direct relation to this one.

**Comment by mstilkerich** [comment] 2024-01-27 12:34
Closing this issue as I cannot reproduce the behavior.

**Closed by mstilkerich** 2024-01-27 12:34 UTC
