### ISSUE TITLE
migration problem

### ISSUE THREAD

**Issue by quenenni** [mstilkerich/rcmcarddav#434] opened 2023-04-19 12:43 UTC
I updated the plugin to the last version.
I saw inthe doc that the db migration process is auto, but I have errors during that process:
```
==> carddav.log <==
[19-Apr-2023 14:34:19 +0200]: <nv6k8196> [1 DBG] carddav::afterLogin
[19-Apr-2023 14:34:19 +0200]: <nv6k8196> [1 DBG] internalGet query: SELECT `filename` FROM carddav_migrations
[19-Apr-2023 14:34:19 +0200]: <nv6k8196> [3 NTC] In migration: 0018-accountentities2

==> errors.log <==
[19-Apr-2023 14:34:19 +0200]: <nv6k8196> DB Error: [1062] Duplicate entry '33-Yyyy' for key 'user_id' (SQL Query: INSERT INTO carddav_accounts (name,username,password,url,user_id,presetname)VALUES ('Address book','%l','{DES_KEY}BYBcPmmh8BmgtUp/z67u5Q==','https://cloud.yyyy.coop/remote.php/dav/addressbooks/users/xxxx/','33','Yyyy')) in /var/www/roundcube-test/program/lib/Roundcube/rcube_db.php on line 567 (GET /index.php/login/oauth?code=e4fb66312301ba078aca57bc5048944420d05cfcba14dfc9db773fd64d09e70c&state=uZwZqN1LBq3Z&session_state=aIytFWpA4XsQItyMurqUAOaTverC6Oky477Oon72kvU%3D.Q0hYQXJUR3dmKzd2cHdBc2UxMnNNZ1A0eGxHeWN4OHpCZUhwTm1rVXllS2VhQVpVWGhpY3dQeXF0YTRVODc4RWo5ZXVNc2JBMVNzVThTSTJGc0phRDE0dDl6NTZWcmltMEhkM1ZIRk5GSzA9)

==> carddav.log <==
[19-Apr-2023 14:34:19 +0200]: <nv6k8196> [5 ERR] Error in PHP-based migration Migration0018: MStilkerich\RCMCardDAV\DBMigrations\Migration0018::migrate account insert failed: [1062] Duplicate entry '33-Yyyy' for key 'user_id'
[19-Apr-2023 14:34:19 +0200]: <nv6k8196> [1 DBG] internalGet query: SELECT * FROM carddav_accounts WHERE ((`user_id` = '1098'))
[19-Apr-2023 14:34:19 +0200]: <nv6k8196> [2 NFO] Adding/Updating preset Yyyy for user 1098

==> errors.log <==
[19-Apr-2023 14:34:19 +0200]: <nv6k8196> DB Error: [1054] Unknown column 'accountname' in 'field list' (SQL Query: INSERT INTO carddav_accounts(`accountname`,`username`,`password`,`discovery_url`,`rediscover_time`,`presetname`,`user_id`) VALUES ('<Account Name>','%z','{DES_KEY}IuvkBn6iCaIZz9jVS3BwTQ==','https://cloud-test.yyyy.coop/.well-known/carddava7','21600','Yyyy','1098')) in /var/www/roundcube-test/program/lib/Roundcube/rcube_db.php on line 567 (GET /index.php/login/oauth?code=e4fb66312301ba078aca57bc5048944420d05cfcba14dfc9db773fd64d09e70c&state=uZwZqN1LBq3Z&session_state=aIytFWpA4XsQItyMurqUAOaTverC6Oky477Oon72kvU%3D.Q0hYQXJUR3dmKzd2cHdBc2UxMnNNZ1A0eGxHeWN4OHpCZUhwTm1rVXllS2VhQVpVWGhpY3dQeXF0YTRVODc4RWo5ZXVNc2JBMVNzVThTSTJGc0phRDE0dDl6NTZWcmltMEhkM1ZIRk5GSzA9)

==> carddav.log <==
[19-Apr-2023 14:34:19 +0200]: <nv6k8196> [1 DBG] INSERT accounts (INSERT INTO carddav_accounts(`accountname`,`username`,`password`,`discovery_url`,`rediscover_time`,`presetname`,`user_id`) VALUES (?,?,?,?,?,?,?)) ->
[19-Apr-2023 14:34:19 +0200]: <nv6k8196> [5 ERR] Database::insert (INSERT INTO carddav_accounts(`accountname`,`username`,`password`,`discovery_url`,`rediscover_time`,`presetname`,`user_id`) VALUES (?,?,?,?,?,?,?)) ERROR: [1054] Unknown column 'accountname' in 'field list'
[19-Apr-2023 14:34:19 +0200]: <nv6k8196> [5 ERR] Error adding/updating preset Yyyy for user 1098 [1054] Unknown column 'accountname' in 'field list'
```

Edit: I went from version 4.3.0 to version 5.0.1.

Edit 2: The carddav_accounts table structure I have:
```
describe carddav_accounts;
+-----------------+------------------+------+-----+---------+----------------+
| Field           | Type             | Null | Key | Default | Extra          |
+-----------------+------------------+------+-----+---------+----------------+
| id              | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| name            | text             | NO   |     | NULL    |                |
| username        | varchar(255)     | NO   |     | NULL    |                |
| password        | text             | NO   |     | NULL    |                |
| url             | varchar(4095)    | YES  |     | NULL    |                |
| user_id         | int(10) unsigned | NO   | MUL | NULL    |                |
| last_discovered | bigint(20)       | NO   |     | 0       |                |
| rediscover_time | int(11)          | NO   |     | 86400   |                |
| presetname      | varchar(255)     | YES  |     | NULL    |                |
+-----------------+------------------+------+-----+---------+----------------+
```

**Comment by quenenni** [comment] 2023-04-19 12:58
Possible the file `plugins/carddav/dbmigrations/0020-distinctcolumnnames/mysql.sql` where not executed beforehand?

The first line seems to be where the column 'name' is changed to 'accountname'.

**Comment by quenenni** [comment] 2023-04-19 14:26
After I changed the line 153 of file `dbmigrations/0018-accountentities2/migrate.php` from:
```
. "(name,username,password,url,user_id,presetname)"
```
to
```
. "(accountname,username,password,discovery_url,user_id,presetname)"
```
It seems to work.

But now, the file `dbmigrations//0020-distinctcolumnnames/mysql.sql` is unhappy:
```
=> carddav.log <==
[19-Apr-2023 16:20:58 +0200]: <sjb544oh> [1 DBG] carddav::afterLogin 
[19-Apr-2023 16:20:58 +0200]: <sjb544oh> [1 DBG] internalGet query: SELECT `filename` FROM carddav_migrations 
[19-Apr-2023 16:20:58 +0200]: <sjb544oh> [3 NTC] In migration: 0020-distinctcolumnnames 
[19-Apr-2023 16:20:58 +0200]: <sjb544oh> [2 NFO] Found 2 queries in /var/www/roundcube-test/plugins/carddav/dbmigrations//0020-distinctcolumnnames/mysql.sql 

==> errors.log <==
[19-Apr-2023 16:20:58 +0200]: <sjb544oh> DB Error: [1054] Unknown column 'name' in 'carddav_accounts' (SQL Query: ALTER TABLE carddav_accounts CHANGE `name` `accountname` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL) in /var/ww
w/roundcube-test/program/lib/Roundcube/rcube_db.php on line 567 (GET /index.php/login/oauth?code=b7b1c43917da52cd1a905d40a25fbaa0cbe4f7c13280eb1ac620df0f14d19efd&state=NlDYU7kpYnnn&session_state=G5xkeVyOCGIuQb2gT%2B%2F0iP4ePpLfo2%2FwU5B6S
pGAa5k%3D.ZjVuVTRmODE0TWJWSUpPMnd3YUZsN1c2UDVadlg5U1U4cDZncGZFSFhnTloza0o0NDZMajFNU3hiZnFTUGVzQ1lKMS9iQkhXbUQ4SXh2OFRxYmdzUXorQmJCeGU0SDQrdXNzaWlQTXRsd289)
```
So ,from my perspective, `dbmigrations//0020-distinctcolumnnames/mysql.sql` should be called before `dbmigrations/0018-accountentities2/migrate.php` and in in the file from 0018, column names 'name' should be 'accountname' and 'url' should be 'discovery_url'

A new error showed, but that's for another ticket to not mix differents issues.

**Comment by quenenni** [comment] 2023-04-19 15:08
> Alternatively, you can also dump all preset accounts from the table, since these will be recreated automatically when the corresponding users login. The only downside is that a full addressbook download will be needed for all contained addressbooks.

That's what I did (as noted in my other issue "migration problem 2") and this step if good now.

**Comment by mstilkerich** [comment] 2023-04-19 16:03
No this is not necessary.

The interesting question is why the accounts table was not empty. If there was an error during the first attempt to migrate, there should be a corresponding error in the logs, but only for the first attempt to migrate, since the subsequent attempts then error out with the duplicate user_id/presetname constraint violation.

**Comment by quenenni** [comment] 2023-04-19 18:27
After lots of tests, I think the migration process when coming from 4.3.0 to 5.0.1 is working if the table carddav_accounts exists and if the table is empty.

If the table doesn't exist, it complains about it  (see below for error).
If the table exists and isn't empty, you have the problems I had in this ticket.

> The interesting question is why the accounts table was not empty

After analysis, I can say it's a very good question.
I went back to my backups.
I started to work on the connexion between Roundcube and Nextcloud mid March (first backup the 16th).
Up to the 21 of March, there was no table carddav_accounts.
On the backup from the 22 of March, the table carddav_accounts was there and filled with data.

I'm very confident I was still working with the older version of this plugin (4.3.0).
I didn't change anything in the plugin, I was just debugging to understand why this plugin was not working anymore with the new OIDC app we are using in Nextcloud.

The last entry of the carddav_migrations table on the 21 and 22 are identicals (`(32,'0015-fixmysqlconstraints','2021-08-02 16:54:37')`) and stayed identicals up to yesterday.

And it was still the same old version of roundcube we were using (1.5.0), I didn't updated it yet. I did it last week.

I have absolutely no clue where this table is coming from.
I don't find any reference to this table in the plugin code from the 22 of March (in version 4.3.0).
I discovered this table with the plugin update process I started yesterday (even if it was alreday there since the 22 of March, I didn't notice it)

About the error I had if the table carddav_accounts didn't exist when entering roundcube with the new plugin version:
```
==> carddav.log <==
[19-Apr-2023 18:58:57 +0200]: <6daq1b5c> [1 DBG] internalGet query: SELECT * FROM carddav_accounts WHERE ((`user_id` = '1098')) 

==> errors.log <==
[19-Apr-2023 18:58:57 +0200]: <6daq1b5c> DB Error: [1146] Table 'roundcubetest.carddav_accounts' doesn't exist (SQL Query: SELECT * FROM carddav_accounts WHERE ((`user_id` = '1098'))) in /var/www/roundcube-test/program/lib/Roundcube/rcube
_db.php on line 567 (GET /?_task=login&_action=oauth)

==> carddav.log <==
[19-Apr-2023 18:58:57 +0200]: <6daq1b5c> [5 ERR] Database::get (SELECT * FROM carddav_accounts WHERE ((`user_id` = '1098'))) ERROR: [1146] Table 'roundcubetest.carddav_accounts' doesn't exist 
[19-Apr-2023 18:58:57 +0200]: <6daq1b5c> [5 ERR] Could not init rcmcarddav: [1146] Table 'roundcubetest.carddav_accounts' doesn't exist
```
It seems your plugin requires it to be there beore starting the migration steps from 4.3.0 to 5.0.1.

Hope this help you understand what happened.

For me, it's good as it is. I know how to have a working migration process.

**Comment by quenenni** [comment] 2023-04-20 14:38
As something was strange, I did an investigation..
I finally found out why I had this table carddav_accounts in my DB.
My colleague, when we first installed our test environment, did a quick attempt to use the last version of the plugin before going back to our used version and I didn't know that.

So, that's why I had this table already there before my migration process.
I don't know why I didn't have anything more in the table carddav_migrations, maybe there was an error on the first step of the migrations and thus nothing was added in that table.

Then, the only problem I had that was coming from the plugin, is the query done on the table carddav_accounts before creating it. 

It looks like the problem behind this issue is identical to this one: #431

**Comment by mstilkerich** [comment] 2023-04-21 15:54
I tried an upgrade, even with an Oauth installation, from 4.3.0 to 5.0.1 for a database where I had several preset accounts including some with multiple addressbooks in the database before the upgrade. It works without problems.

Therefore, I believe the issue you experienced are from a broken database (upgrade to v5, then downgrade (which is not supported), and probably some meddling with the database to get v4.3.0 working with a database again that had already been upgraded to v5 before, i.e. attempt to manually convert the database back to v4 without deleting the accounts table).

Anyway, I cannot reproduce this and therefore will close the issue.

**Closed by mstilkerich** 2023-04-21 15:54 UTC

**Comment by foorschtbar** [comment] 2024-05-21 14:50
Same problem here with a fresh installation of 5.1. Same error message. After running the init script and login everything works fine.

**Comment by mstilkerich** [comment] 2024-05-29 17:46
What error message exactly are you referring to? Author of this issue was not using a fresh install.

**Comment by foorschtbar** [comment] 2024-06-03 08:57
the 
```
DB Error: [1146] Table 'roundcubetest.carddav_accounts' doesn't exist (SQL Query: SELECT * FROM carddav_accounts WHERE ((`user_id` = '1098'))) in /var/www/roundcube-test/program/lib/Roundcube/rcube
_db.php on line 567 (GET /?_task=login)```

Can`t reproduce with fresh db. Deleting only the tables wont work for me.

**Comment by mstilkerich** [comment] 2024-06-03 18:02
Are you using the twofactor_gauthenticator plugin?

If so see #175 for issue description and workaround.

**Comment by foorschtbar** [comment] 2024-06-04 08:12
Yes, i use the `twofactor_gauthenticator` plugin and a yes, i just reorder the plugins and `carddav` is befor `twofactor_gauthenticator`.
