### ISSUE TITLE
PHP Fatal error: MStilkerich\RCMCardDAV\Frontend\RcmInterface

### ISSUE THREAD

**Issue by jaro3** [mstilkerich/rcmcarddav#418] opened 2023-01-20 04:00 UTC
Current version crashes both under  php-fpm 8.2.1-1 or php-legacy-fpm 8.1.14-3:

PHP Fatal error:  Uncaught Error: Interface "MStilkerich\RCMCardDAV\Frontend\RcmInterface" not found in /usr/share/webapps/roundcubemail/plugins/carddav/carddav.php:35
Stack trace:
#0 /usr/share/webapps/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(204): include()
#1 /usr/share/webapps/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(126): rcube_plugin_api->load_plugin()
#2 /usr/share/webapps/roundcubemail/program/include/rcmail.php(108): rcube_plugin_api->load_plugins()
#3 /usr/share/webapps/roundcubemail/program/include/rcmail.php(86): rcmail->startup()
#4 /usr/share/webapps/roundcubemail/index.php(43): rcmail::get_instance()
#5 {main}
  thrown in /usr/share/webapps/roundcubemail/plugins/carddav/carddav.php on line 35

This is on current Arch Linux:

roundcubemail 1.6.0-1
roundcubemail-plugin-carddav 5.0.0-1

**Comment by mstilkerich** [comment] 2023-01-20 05:04
Hello, duplicate of #415, I guess?

**Comment by mstilkerich** [comment] 2023-01-20 05:10
The arch package for 5.0.0 is simply built from the github tarball. This one does not include dependencies, so this cannot work.

https://aur.archlinux.org/cgit/aur.git/diff/?h=roundcubemail-plugin-carddav

I have pulled the release tarball because of #415 and also put a bold face note at the top of the release notes that there is no tarball for 5.0.0, it can only be installed using composer.

I will release 5.0.1 with a fix and a tarball this weekend.

**Closed by mstilkerich** 2023-01-20 05:10 UTC

**Comment by mstilkerich** [comment] 2023-01-20 18:59
5.0.1 is out and should fix the issue with the tarball.
